// Mapped Type untuk key dan value yang sama
export const APP_PERMISSIONS = {
  "add-user": "add-user",
  "edit-user": "edit-user",
  "view-user": "view-user",
  "delete-user": "delete-user",
  "add-role": "add-role",
  "edit-role": "edit-role",
  "change-role-permission": "change-role-permission",
  "delete-role": "delete-role",
  "set-user-role": "set-user-role",
  "view-apps": "view-apps",
  payment: "payment",
  "view-role": "view-role",
  "view-permission": "view-permission",
  "create-division": "create-division",
  "update-division": "update-division",
  "delete-division": "delete-division",
  "view-division": "view-division",
  "view-shift": "view-shift",
  "create-shift": "create-shift",
  "update-shift": "update-shift",
  "delete-shift": "delete-shift",
  "view-leave": "view-leave",
  "update-leave": "update-leave",
  "delete-leave": "delete-leave",
  "create-staff": "create-staff",
  "update-staff": "update-staff",
  "delete-staff": "delete-staff",
  "view-staff": "view-staff",
  "update-absen": "update-absen",
  "delete-absen": "delete-absen",
  "view-absen": "view-absen",
  "update-overtime": "update-overtime",
  "delete-overtime": "delete-overtime",
  "view-overtime": "view-overtime",
  "view-laporan": "view-laporan",
  "export-laporan": "export-laporan",
  "create-hari-libur": "create-hari-libur",
  "update-hari-libur": "update-hari-libur",
  "delete-hari-libur": "delete-hari-libur",
  "view-hari-libur": "view-hari-libur",
  "create-payroll": "create-payroll",
  "update-payroll": "update-payroll",
  "delete-payroll": "delete-payroll",
  "view-payroll": "view-payroll",
  "create-kpi-divisi": "create-kpi-divisi",
  "update-kpi-divisi": "update-kpi-divisi",
  "delete-kpi-divisi": "delete-kpi-divisi",
  "view-kpi-divisi": "view-kpi-divisi",
  "create-kpi-staff": "create-kpi-staff",
  "update-kpi-staff": "update-kpi-staff",
  "delete-kpi-staff": "delete-kpi-staff",
  "view-kpi-staff": "view-kpi-staff",
  "view-salary": "view-salary",
} as const;

export type AppPermission = keyof typeof APP_PERMISSIONS;

// Array berdasarkan object APP_PERMISSIONS
export const PERMISSION_ARRAY = Object.keys(APP_PERMISSIONS) as AppPermission[];
