export const HRD_PERMISSIONS = {
  CREATE_DIVISION: "create-division",
  UPDATE_DIVISION: "update-division",
  DELETE_DIVISION: "delete-division",
  VIEW_DIVISION: "view-division",
  VIEW_SHIFT: "view-shift",
  CREATE_SHIFT: "create-shift",
  UPDATE_SHIFT: "update-shift",
  DELETE_SHIFT: "delete-shift",
  VIEW_LEAVE: "view-leave",
  UPDATE_LEAVE: "update-leave",
  DELETE_LEAVE: "delete-leave",
  CREATE_STAFF: "create-staff",
  UPDATE_STAFF: "update-staff",
  DELETE_STAFF: "delete-staff",
  VIEW_STAFF: "view-staff",
  UPDATE_ABSEN: "update-absen",
  DELETE_ABSEN: "delete-absen",
  VIEW_ABSEN: "view-absen",
  UPDATE_OVERTIME: "update-overtime",
  DELETE_OVERTIME: "delete-overtime",
  VIEW_OVERTIME: "view-overtime",
  VIEW_LAPORAN: "view-laporan",
};
